channels:
    - conda-forge
dependencies:
    - python=3.8
    - pytables # install pytables for macOS arm64, so do not need to build from source.
    - liblsl # install liblsl to prevent error on macOS and Ubuntu: "RuntimeError: LSL binary library file was not found."
    - wxpython # install pytables to prevent error on macOS: "site-packages/wx/_core.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '__ZN10wxBoxSizer20InformFirstDirectionEiii'"